export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  jwtSecret: process.env.JWT_SECRET ?? "your-secret-key-change-in-production",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  ownerName: process.env.OWNER_NAME ?? "Admin",
  isProduction: process.env.NODE_ENV === "production",
  nodeEnv: process.env.NODE_ENV ?? "development",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  appPort: parseInt(process.env.APP_PORT ?? "3000"),
  appHost: process.env.APP_HOST ?? "localhost",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  smtpHost: process.env.SMTP_HOST ?? "localhost",
  smtpPort: parseInt(process.env.SMTP_PORT ?? "587"),
  smtpUser: process.env.SMTP_USER ?? "",
  smtpPass: process.env.SMTP_PASS ?? "",
  openaiApiKey: process.env.OPENAI_API_KEY ?? "",
  storageProvider: process.env.STORAGE_PROVIDER ?? "local",
  storagePath: process.env.STORAGE_PATH ?? "/data/uploads",
};
